# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_linkorgsonnx_wrappers", use_symbols = TRUE, package_name = "linkorgsonnx")

#' @usage NULL
#' @useDynLib linkorgsonnx, .registration = TRUE
NULL

hnsw_join <- function(a_mat, b_mat) .Call(wrap__hnsw_join, a_mat, b_mat)

ORTSession <- new.env(parent = emptyenv())

ORTSession$new_from_path <- function(num_threads, path, tokenizer_path) .Call(wrap__ORTSession__new_from_path, num_threads, path, tokenizer_path)

ORTSession$run_model <- function(inputs) .Call(wrap__ORTSession__run_model, self, inputs)

#' @export
`$.ORTSession` <- function (self, name) { func <- ORTSession[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ORTSession` <- `$.ORTSession`


# nolint end
