# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_linkorgsonnx_wrappers", use_symbols = TRUE, package_name = "linkorgsonnx")

#' @usage NULL
#' @useDynLib linkorgsonnx, .registration = TRUE
NULL

ORTSession <- new.env(parent = emptyenv())

ORTSession$new_from_url <- function(num_threads, url) .Call(wrap__ORTSession__new_from_url, num_threads, url)

ORTSession$new_from_path <- function(num_threads, path) .Call(wrap__ORTSession__new_from_path, num_threads, path)

ORTSession$run_model <- function(x) invisible(.Call(wrap__ORTSession__run_model, self, x))

#' @export
`$.ORTSession` <- function (self, name) { func <- ORTSession[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ORTSession` <- `$.ORTSession`


# nolint end
